--[[
    Constants for Forgotten Tales


]]

VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 224

WINDOW_WIDTH = 960
WINDOW_HEIGHT = 720

TINY_GUI_TILE_SIZE = 16
SMALL_GUI_TILE_SIZE = 16
GUI_TILE_SIZE = 16
TILE_SIZE = 32

SCREEN_TILE_WIDTH = VIRTUAL_WIDTH / TILE_SIZE
SCREEN_TILE_HEIGHT = VIRTUAL_HEIGHT / TILE_SIZE

CAMERA_SPEED = 1

EMPTY_SPACE = 25

DEBUG = false

CHAR_TWEEN_DURATION = 0.3